# Use an OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory to /app
WORKDIR /app

# Copy the project's JAR file from the target directory into the container
COPY target/order-service.jar app.jar

# Run the command to launch the Spring Boot application when the container starts up
CMD ["java", "-jar", "app.jar"]
